### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by brauner** [hallyn/libresource#1]
I would certainly be ready to do some work. Depending on my current work load it might sometimes take a little while but if you feel I could be of some help... Which languages are we talking `C`?

**Comment by hallyn** [comment]
Yup, I'm thinking straight C.  We can provide bindings for whatever languages people want.

Would you like to make a pull request adding yourself to contributors?

**Comment by hallyn** [comment]
Sorry for the delayed reply - i need to direct emails about this git tree to my inbox.

**Comment by brauner** [comment]
Yes, will do. Thanks, and no worries.
